version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/marp

commands:
  install_dependencies:
    description: Install dependencies
    parameters:
      cache_key:
        type: string
        default: '{{ .Environment.CIRCLE_JOB }}'
    steps:
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CI_CACHE_PREFIX }}-<< parameters.cache_key >>-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - dependencies-{{ .Environment.CI_CACHE_PREFIX }}-<< parameters.cache_key >>-{{ checksum "yarn.lock" }}-
            - dependencies-{{ .Environment.CI_CACHE_PREFIX }}-<< parameters.cache_key >>-

      - run: yarn install
      - run: yarn audit

      - save_cache:
          key: dependencies-{{ .Environment.CI_CACHE_PREFIX }}-<< parameters.cache_key >>-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

jobs:
  build:
    executor:
      name: node
    steps:
      - run: node --version
      - checkout
      - install_dependencies

      - run:
          name: Prettier formatting
          command: yarn check:format

workflows:
  build:
    jobs:
      - build
